on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to verify PDF
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Verify the PDF file
        id: verify
        uses: jdujava/cuni-thesis-validator@v3
        with:
          pdf_file: thesis.pdf
      - name: Get the return value of verify
        run: echo "Verify status -> ${{ steps.verify.outputs.is_valid }}"
