on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to verify PDF
    steps:
      - name: Verify the PDF file
        id: verify
        uses: jdujava/cuni-thesis-validator@v2
        with:
          pdf_file: thesis.pdf
      # Echo the valiadtion report
      - name: Get the return value of verify
        run: echo "Verify status: ${{ steps.verify.outputs.is_valid }}"
