name: Test storage and verification of a PDF-A file
on: [push]

jobs:
  verify_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      # - name: Compile LaTeX document
      #   uses: dante-ev/latex-action@latest
      #   with:
      #     root_file: thesis.tex
      - name: Get the date
        run: echo "DATE=$(date '+%d-%m-%Y_%H-%M')" >> "$GITHUB_ENV"
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: thesis_${{ env.DATE }}
          path: thesis.pdf
      - name: Verify the PDF file
        id: verify
        uses: jdujava/cuni-thesis-validator@v4
        with:
          pdf_file: thesis.pdf
      - name: Get the return value of verify
        run: echo "Verify status -> ${{ steps.verify.outputs.is_valid }}"
